import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

import { LANGUAGES, SOURCE_LANGUAGE, type LanguageCode } from '@mia/validators/language';

import { pushStringEntries, type PushStringEntry } from '../src/push-strings.ts';

/**
 * Generates the native string resources the mobile app compiles into its bundle.
 *
 * A push is drawn by the OS while the app is closed, so the wording cannot come
 * from our API or from the app's JavaScript i18n bundle — nothing of ours is
 * running. It has to already be in `strings.xml` and `Localizable.strings`. This
 * script is what keeps that from becoming a second copy of the copy: the catalogue
 * stays in `@mia/i18n`, and these files are build output.
 *
 *   pnpm --filter @mia/i18n run generate:native
 *
 * The output directory is gitignored here and COMMITTED in the app repository.
 * That split is deliberate — for us they are artefacts, for the app they are
 * source that has to be in the build.
 *
 * ⚠️ Regenerating is half the job. New keys only work on builds that shipped them,
 * so bumping `LOCALIZED_STRINGS_SINCE` in `modules/push/message.ts` to the app
 * version that will carry them belongs in the same commit. Without it the server
 * sends a key the installed app has never heard of, and iOS renders the raw key
 * on somebody's lock screen.
 */

const OUT_DIR = join(dirname(fileURLToPath(import.meta.url)), '..', 'generated', 'native');

/**
 * Android wants the source language in bare `values/` and everything else in
 * `values-<code>/`; iOS wants `<code>.lproj` for all of them including the
 * source. Getting this wrong is silent — the device simply falls back — so the
 * asymmetry is encoded here rather than left to whoever wires the app.
 */
function androidDir(code: LanguageCode): string {
  return code === SOURCE_LANGUAGE ? 'values' : `values-${code}`;
}

/**
 * `{0}` → `%1$s`. Android's positional form is explicitly indexed rather than a
 * bare `%s`, because a language whose grammar wants the arguments in another
 * order must be able to reorder them without the call site changing.
 */
function androidText(template: string): string {
  return escapeAndroid(template).replace(
    /\{(\d+)\}/g,
    (_, index: string) => `%${Number(index) + 1}$s`,
  );
}

/**
 * Android's XML string format, which is not XML escaping alone: an apostrophe or
 * a double quote inside a resource is a syntax error unless backslash-escaped,
 * and our Italian and French copy is full of them.
 */
function escapeAndroid(value: string): string {
  return value
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/\\/g, '\\\\')
    .replace(/'/g, "\\'")
    .replace(/"/g, '\\"');
}

/** `{0}` → `%1$@`. iOS takes objects, not C strings, for substituted text. */
function appleText(template: string): string {
  return template
    .replace(/\\/g, '\\\\')
    .replace(/"/g, '\\"')
    .replace(/\{(\d+)\}/g, (_, index: string) => `%${Number(index) + 1}$@`);
}

function androidFile(entries: PushStringEntry[], code: LanguageCode): string {
  const lines = entries.flatMap((entry) => [
    `  <string name="${entry.key}_title">${androidText(entry.title[code])}</string>`,
    `  <string name="${entry.key}_body">${androidText(entry.body[code])}</string>`,
  ]);

  return [
    '<?xml version="1.0" encoding="utf-8"?>',
    '<!-- GENERATED by @mia/i18n — do not edit. Change the copy in packages/i18n. -->',
    '<resources>',
    ...lines,
    '</resources>',
    '',
  ].join('\n');
}

function appleFile(entries: PushStringEntry[], code: LanguageCode): string {
  const lines = entries.flatMap((entry) => [
    `"${entry.key}_title" = "${appleText(entry.title[code])}";`,
    `"${entry.key}_body" = "${appleText(entry.body[code])}";`,
  ]);

  return [
    '/* GENERATED by @mia/i18n — do not edit. Change the copy in packages/i18n. */',
    ...lines,
    '',
  ].join('\n');
}

const entries = pushStringEntries();

for (const language of LANGUAGES) {
  const android = join(OUT_DIR, 'android', androidDir(language.code));
  mkdirSync(android, { recursive: true });
  writeFileSync(join(android, 'strings.xml'), androidFile(entries, language.code));

  const apple = join(OUT_DIR, 'ios', `${language.code}.lproj`);
  mkdirSync(apple, { recursive: true });
  writeFileSync(join(apple, 'Localizable.strings'), appleFile(entries, language.code));
}

console.log(
  `[i18n] ${entries.length} push strings → ${LANGUAGES.length} languages, android + ios, in ${OUT_DIR}`,
);
