/**
 * shadcn-svelte's utility module. Generated by `shadcn-svelte init`, with one
 * deliberate change: `cn` comes from cnfast rather than clsx + tailwind-merge.
 *
 * cnfast is a drop-in with byte-identical output and no runtime dependencies of
 * its own, so every generated component keeps working untouched. Re-exported
 * from here — rather than imported directly at call sites — so this stays the
 * single place the implementation is decided.
 */

export { cn } from 'cnfast';
export type { ClassValue } from 'cnfast';

export type WithoutChild<T> = T extends { child?: unknown } ? Omit<T, 'child'> : T;
export type WithoutChildren<T> = T extends { children?: unknown } ? Omit<T, 'children'> : T;
export type WithoutChildrenOrChild<T> = WithoutChildren<WithoutChild<T>>;
export type WithElementRef<T, U extends HTMLElement = HTMLElement> = T & { ref?: U | null };
